apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  project: task-manager
  source:
    repoURL: https://github.com/suryaparua-official/Distributed-Task-Management-System.git
    targetRevision: main
    path: observability/elk/filebeat
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
