replicaCount: 2

image:
  repository: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/task-manager/user-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1

env:
  PORT: "5000"
  NODE_ENV: "production"

externalSecret:
  secretName: user-service-secrets

probes:
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 20

istio:
  inject: "true"
